-- vim.o.hidden=true --Required to keep multiple buffers open
-- vim.wo.wrap=false --Display long lines as just one line
vim.o.splitbelow=true --Horizontal splits will automatically be below
vim.o.splitright=true --Vertical splits will automatically be to the right
vim.wo.number = true -- show line number
vim.wo.relativenumber = true -- show relative line number
vim.wo.cursorline=true --Enable highlighting of the current line
vim.o.showmode=false --We don't need to see things like -- INSERT -- anymore
vim.o.clipboard="unnamedplus" --Copy paste between vim and everything else
